version: "3.9"

services:
  elasticsearch-gui:
   image: cars10/elasticvue
   ports:
     - "8888:8080"
   depends_on:
     - elasticsearch

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
   ports:
     - "9200:9200"
   environment:
     - discovery.type=single-node
     - http.cors.enabled=true
     - http.cors.allow-origin=http://localhost:8888

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: .
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./.data:/usr/src/app/.data
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
volumes:
  static_volume:
  media_volume: