version: "3.9"

services:
  elasticsearch-gui:
   image: cars10/elasticvue
   ports:
     - "8088:8080"
#   depends_on:
#     - elasticsearch

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
#   container_name: elasticsearch
   ports:
     - "9200:9200"
#     - "9300:9300"
   environment:
     - discovery.type=single-node
     - http.cors.enabled=true
     - http.cors.allow-origin=http://localhost:8080

#  db:
#    image: postgres:12.0
#    volumes:
#      - ./.data/db:/var/lib/postgresql/data  2021-10-22T08:12:10,797Z
#    env_file:
#      - ./.env
#    ports:
#    - "5432:5432"
  app:
    build: .
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 -w 4
#    command: python manage.py runserver 0.0.0.0:8000
#    command: ls -lah
#    volumes:
#      - ./media_dir:/usr/src/app/media
#      - ./static_dir:/usr/src/app/static
#      - ./.data:/usr/src/app/.data
    ports:
      - "8000:8000"
    env_file:
      - ./.env
#    depends_on:
#      - db
#      - elasticsearch
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
