# Конфигурация модели детектирования животных.
detector:

  # Путь до весов модели.
  weights_path: ml_models/yolox_l.onnx

  # Размер изображения, с которыми будет работать детектор.
  image_size:
    - 640
    - 640

  # Порог для отсечки по вероятности.
  score_thresh: 0.5

  # Порог для отсечки для алгоритма подавления немаксимумов.
  nms_thresh: 0.45

  # Список классов объектов, которые мы хотим искать.
  accepted_classes:
    - dog

# Конфигурация для OCR модели.
ocr:

  # Допустимые префиксы ID камер.
  id_prefixes:
    - PVN
    - DVN
    - MMC

  # Максимальное значение пикселя.
  max_pixel_intensity: 255

  # Минимальное значение пикселя.
  min_pixel_intensity: 180

# Конфигурация модели распознавания длины хвоста.
tail_model:

  # Путь до весов модели.
  weights_path: ml_models/tail.onnx

  # Размер изображения, с которыми будет работать модель.
  image_size:
    - 224
    - 224

# Конфигурация модели распознавания оттенка шерсти.
color_model:

  # Путь до весов модели.
  weights_path: ml_models/color.onnx

  # Размер изображения, с которыми будет работать модель.
  image_size:
    - 224
    - 224

  # Список с именами классов оттенков шерсти.
  classes:
    - bright 
    - dark
    - ginger
    - multi_color

# Конфигурация модели распознавание породы собак.
breed_model:

# Путь до весов модели.
  weights_path: ml_models/breed.onnx

  # Размер изображения, с которыми будет работать модель.
  image_size:
    - 224
    - 224

  # Список с именами классов оттенков шерсти.
  classes:
    - affenpinscher
    - afghan_hound
    - african_hunting_dog
    - airedale
    - american_staffordshire_terrier
    - appenzeller
    - australian_terrier
    - basenji
    - basset
    - beagle
    - bedlington_terrier
    - bernese_mountain_dog
    - black-and-tan_coonhound
    - blenheim_spaniel
    - bloodhound
    - bluetick
    - border_collie
    - border_terrier
    - borzoi
    - boston_bull
    - bouvier_des_flandres
    - boxer
    - brabancon_griffon
    - briard
    - brittany_spaniel
    - bull_mastiff
    - cairn
    - cardigan
    - chesapeake_bay_retriever
    - chihuahua
    - chow
    - clumber
    - cocker_spaniel
    - collie
    - curly-coated_retriever
    - dandie_dinmont
    - dhole
    - dingo
    - doberman
    - english_foxhound
    - english_setter
    - english_springer
    - entlebucher
    - eskimo_dog
    - flat-coated_retriever
    - french_bulldog
    - german_shepherd
    - german_short-haired_pointer
    - giant_schnauzer
    - golden_retriever
    - gordon_setter
    - great_dane
    - great_pyrenees
    - greater_swiss_mountain_dog
    - groenendael
    - ibizan_hound
    - irish_setter
    - irish_terrier
    - irish_water_spaniel
    - irish_wolfhound
    - italian_greyhound
    - japanese_spaniel
    - keeshond
    - kelpie
    - kerry_blue_terrier
    - komondor
    - kuvasz
    - labrador_retriever
    - lakeland_terrier
    - leonberg
    - lhasa
    - malamute
    - malinois
    - maltese_dog
    - mexican_hairless
    - miniature_pinscher
    - miniature_poodle
    - miniature_schnauzer
    - newfoundland
    - norfolk_terrier
    - norwegian_elkhound
    - norwich_terrier
    - old_english_sheepdog
    - otterhound
    - papillon
    - pekinese
    - pembroke
    - pomeranian
    - pug
    - redbone
    - rhodesian_ridgeback
    - rottweiler
    - saint_bernard
    - saluki
    - samoyed
    - schipperke
    - scotch_terrier
    - scottish_deerhound
    - sealyham_terrier
    - shetland_sheepdog
    - shih-tzu
    - siberian_husky
    - silky_terrier
    - soft-coated_wheaten_terrier
    - staffordshire_bullterrier
    - standard_poodle
    - standard_schnauzer
    - sussex_spaniel
    - tibetan_mastiff
    - tibetan_terrier
    - toy_poodle
    - toy_terrier
    - vizsla
    - walker_hound
    - weimaraner
    - welsh_springer_spaniel
    - west_highland_white_terrier
    - whippet
    - wire-haired_fox_terrier
    - yorkshire_terrier