# Generated by Django 3.2.8 on 2021-10-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VidecamFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frames')),
                ('videcam_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1000)),
                ('breed', models.CharField(max_length=4000)),
                ('long_tail_proba', models.FloatField()),
                ('top_left_x', models.FloatField()),
                ('top_left_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='search.videcamframe')),
            ],
        ),
    ]
