# Generated by Django 3.2.8 on 2021-10-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidecamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videcam_id', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='videcamframe',
            name='videcam_id',
        ),
        migrations.AddField(
            model_name='videcamframe',
            name='videcam_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.videcaminfo'),
        ),
    ]
