# Generated by Django 3.2.8 on 2021-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_videcam_info_videcamframe_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='videcaminfo',
            name='ovd_phones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
